In [3]:
import numpy

In [4]:
numbers_list = [1,2,3,4,5]

In [5]:
numbers_list

[1, 2, 3, 4, 5]

In [6]:
numbers_list + numbers_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [8]:
# create a numpy array
numbers_array = numpy.array(numbers_list)
numbers_array

array([1, 2, 3, 4, 5])

In [9]:
numbers_array + numbers_array

array([ 2,  4,  6,  8, 10])

In [11]:
numbers_array / numbers_array

array([1., 1., 1., 1., 1.])

In [12]:
numbers_array  * 10

array([10, 20, 30, 40, 50])

In [13]:
len(numbers_array)

5

In [14]:
numbers_array.size

5

In [16]:
numpy.concatenate([numbers_array, numbers_array])

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [19]:
a = 10
b = 20

difference = a - b
difference

-10

In [20]:
numpy.abs(difference)

np.int64(10)

In [22]:
numbers_array_1 = numpy.array([10, 16, 8, 3, 44])
numbers_array_2 = numpy.array([6, 20, 15, 1, 63])

In [24]:
numpy.abs(numbers_array_1 - numbers_array_2)

array([ 4,  4,  7,  2, 19])

In [28]:
# filtering
numbers_array_1[numbers_array_1 < 10]


array([8, 3])

In [27]:
numbers_array_1

array([10, 16,  8,  3, 44])

In [31]:
numbers_array_1

array([10, 16,  8,  3, 44])

In [35]:
numbers_array_1_b = numpy.where(numbers_array_1 < 10, 10, numbers_array_1)
numbers_array_1_b

array([10, 16, 10, 10, 44])

In [61]:
filtered_values = numpy.array([8, 3])

numpy.where(numpy.isin(numbers_array_1, filtered_values), "Yes", "No")

array(['No', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

In [63]:
numpy.isin(numbers_array_1, filtered_values)

array([False, False,  True,  True, False])

In [64]:
numbers_array_1

array([10, 16,  8,  3, 44])