In [3]:
import numpy

In [4]:
numbers_list = [1,2,3,4,5]

In [5]:
numbers_list

[1, 2, 3, 4, 5]

In [6]:
numbers_list + numbers_list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [8]:
# create a numpy array
numbers_array = numpy.array(numbers_list)
numbers_array

array([1, 2, 3, 4, 5])

In [9]:
numbers_array + numbers_array

array([ 2,  4,  6,  8, 10])

In [11]:
numbers_array / numbers_array

array([1., 1., 1., 1., 1.])

In [12]:
numbers_array  * 10

array([10, 20, 30, 40, 50])

In [13]:
len(numbers_array)

5

In [14]:
numbers_array.size

5

In [16]:
numpy.concatenate([numbers_array, numbers_array])

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [19]:
a = 10
b = 20

difference = a - b
difference

-10

In [20]:
numpy.abs(difference)

np.int64(10)

In [22]:
numbers_array_1 = numpy.array([10, 16, 8, 3, 44])
numbers_array_2 = numpy.array([6, 20, 15, 1, 63])

In [24]:
numpy.abs(numbers_array_1 - numbers_array_2)

array([ 4,  4,  7,  2, 19])

In [28]:
# filtering
numbers_array_1[numbers_array_1 < 10]


array([8, 3])

In [27]:
numbers_array_1

array([10, 16,  8,  3, 44])

In [31]:
numbers_array_1

array([10, 16,  8,  3, 44])

In [35]:
numbers_array_1_b = numpy.where(numbers_array_1 < 10, 10, numbers_array_1)
numbers_array_1_b

array([10, 16, 10, 10, 44])

In [61]:
filtered_values = numpy.array([8, 3])

numpy.where(numpy.isin(numbers_array_1, filtered_values), "Yes", "No")

array(['No', 'No', 'Yes', 'Yes', 'No'], dtype='<U3')

In [63]:
numpy.isin(numbers_array_1, filtered_values)

array([False, False,  True,  True, False])

In [65]:
numpy.pi

3.141592653589793

# Assignments

In [68]:
# 1. 
my_array_1 = numpy.array([20, 56])
my_array_2 = numpy.array([11, 78])
my_array_3 = numpy.array([43, 65])

my_array_3

array([43, 65])

In [69]:
# 2. Combine the arrays to a single array called diameters
diameters = numpy.concatenate([my_array_1, my_array_2, my_array_3])
diameters


array([20, 56, 11, 78, 43, 65])

In [70]:
# 3. Define a function (calc_circle) that calculates the size of a circle: (diameter / 2) ^ 2 * pi
def calc_circle(diameter):
    radius = diameter / 2
    size = radius ** 2 * numpy.pi
    return size


In [71]:
# 4. Create a new array sizes_circle based on the calc_circle function applied to the 
# diameters that will contain the sizes of the circle based on the diameters in the diameters array.

sizes_circle = []

for diameter in diameters:
    size = calc_circle(diameter)
    sizes_circle.append(size)

sizes_circle_array = numpy.array(sizes_circle)
sizes_circle_array

array([ 314.15926536, 2463.00864041,   95.03317777, 4778.36242611,
       1452.20120412, 3318.30724035])

In [79]:
# 5.  Filter the sizes_circle array for only values above the avarage value of the sizes_circle array.
average_size = numpy.mean(sizes_circle_array)

sizes_circle_array[sizes_circle_array > average_size]

array([2463.00864041, 4778.36242611, 3318.30724035])

In [86]:
# 6. Create a function that prints the following information from the sizes_circle array:
'''
- The number of values,
- standard deviation,
- min and max values
- the unique values
- the number of unique values
'''

def display_info_array(input_array):
    num_values = input_array.size
    std_value = input_array.std()
    min_value = input_array.min()
    max_value = input_array.max()
    unique_values = numpy.unique(input_array)
    num_unique_values = unique_values.size

    # print the values
    line = f"""
            Num values         : {num_values}
            Standard deviation : {std_value}
            Min value          : {min_value}
            Max value          : {max_value}
            Unique values      : {unique_values}
            Num unique values  : {num_unique_values}
            """
    print(line)


display_info_array(sizes_circle_array)


            Num values         : 6
            Standard deviation : 1653.9397199782222
            Min value          : 95.03317777109125
            Max value          : 4778.362426110075
            Unique values      : [  95.03317777  314.15926536 1452.20120412 2463.00864041 3318.30724035
 4778.36242611]
            Num unique values  : 6
            


In [87]:
diameters

array([20, 56, 11, 78, 43, 65])

In [88]:
# 7. Create a function, split_odd_even that accepts a numpy array and 
# returns the odd and even numbers in two seperate arrays.

def split_odd_even(input_array):
    odd_array = input_array[input_array % 2 == 1]
    even_array = input_array[input_array % 2 == 0]

    return odd_array, even_array

    

In [94]:
# 8. Apply the split_odd_even function to both the diameters and sizes_circle arrays.
result_odd, result_even = split_odd_even(diameters)

In [95]:
result_odd

array([11, 43, 65])

In [96]:
result_even

array([20, 56, 78])

In [97]:
split_odd_even(sizes_circle_array)

(array([], dtype=float64), array([], dtype=float64))

In [98]:
sizes_circle_array

array([ 314.15926536, 2463.00864041,   95.03317777, 4778.36242611,
       1452.20120412, 3318.30724035])